name: Build, Lint, Type-check

on:
  workflow_run:
    workflows: ["Setup Project"]
    types:
      - completed

jobs:
  build-lint-typecheck:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Build, lint and type-check
        run: pnpm turbo build lint format typecheck

  # run-snyk:
  #   concurrency:
  #     group: testing
  #     cancel-in-progress: true
  #   runs-on: ubuntu-latest
  #   if: success()
  #   steps:
  #     - name: Run Snyk to check for vulnerabilities
  #       uses: snyk/actions/node@master
  #       continue-on-error: true
  #       env:
  #         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  #       with:
  #         args: --sarif-file-output=snyk.sarif
  #     - name: Upload result to GitHub Code Scanning
  #       uses: github/codeql-action/upload-sarif@v2
  #       with:
  #         sarif_file: snyk.sarif
