name: Build, Lint, Type-check

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

jobs:
  build-lint-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Build, lint and type-check
        run: pnpm turbo build lint format typecheck

  run-snyk:
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
